services:
  weather-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379" # Map Redis port
